### ISSUE TITLE
This project has not reached version 1.0.

### ISSUE THREAD

**Issue by pendingchaos** [dartydevil/Crazy-monkey-artwork#4]

**Comment by dartydevil** [comment]
FINN what are you doing right now???

**Comment by pendingchaos** [comment]
Blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah.

**Comment by dartydevil** [comment]
TICK

**Comment by dartydevil** [comment]
TOCK

**Comment by dartydevil** [comment]
GOES THE CLOCK

**Comment by PuppyWuppy10** [comment]
O.O What....

**Comment by dartydevil** [comment]
V.1 will be released on local computers at 14:30 GMT +1 30/7/15
